config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers, :dmRoom
    end
  end
  root 'posts#index' 
  resources :messages, only: [:create]
  resources :rooms, only: [:new, :create, :show, :index, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, except: :show
  get   'users/:id'   =>  'users#show'

  resources :notifications, only: :index
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :posts

  mount_uploader :image, ImageUploader
# フォロー機能のアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
# 通知機能のアソシエーション
  # has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  # has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
      room = Room.find(params[:room_id])
      last_message_id = params[:id].to_i
      @messages = room.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(user_id: current_user.id))
      if @message.save
        respond_to do |format|
          format.html {redirect_to "/rooms/#{@message.room_id}", notice: 'メッセージが送信されました'}
          format.json {}
        end
      else
        render :index
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def create
    Post.create(image: post_params[:image], text: post_params[:text], user_id: current_user.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post.user_id == current_user.id
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.update(post_params)
    end
  end

  private
  def post_params
    params.permit(:image, :text)
  end

  def move_to_index
  redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:success] = 'フォローしました'
      redirect_to user
    else
      flash.now[:alert] = 'フォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:success] = 'フォローを解除しました'
      redirect_to user
    else
      flash.now[:alert] = 'フォロー解除に失敗しました'
      redirect_to user
    end
  end

  private

  def set_user
    user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries.where.not(user_id: current_user.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :edit
  def index
    @users=User.where.not(id: current_user.id).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     flash[:success] = "Profile updated"
  #     redirect_to @user
  #   else
  #     render :edit
  #   end
  # end

  def dmRoom
    @user = current_user
    @currentEntries = current_user.entries
    dmRoomIds = []
    
    @currentEntries.each do |entry|
    dmRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: dmRoomIds).where.not(user_id: @user).order(created_at: :desc).page(params[:page]).per(5)
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image)
  end

  def after_login
    current_user.update(first_sign_in_at: current_user.current_sign_in_at) unless current_user.first_sign_in_at
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SnsApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_post.html.haml
.main-contents
  .card
    -# .card-img
      -# - if post.image.present?
      -#   = image_tag src="#{post.image}", size: "500x300" 
      -# - else
      -#   = image_tag src='no-image.png', size: "500x300"
    .card-content
      .card-content__left
        .card-content__left__name
          %a{href: "/users/#{post.user.id}"}
            = post.user.name
      .card-content__right
        .card-content__right__top
          .card-content__right__top__date
            = post.created_at.strftime("%Y/%m/%d %H:%M")
          - if user_signed_in? && current_user.id == post.user_id
            = link_to '編集', edit_post_path(post.id), class: "post-edit", method: :get
            = link_to '削除', "/posts/#{post.id}", class: "post-delete", method: :delete
        .card-content__right__bottom
          .card-content__right__bottom__text
            = simple_format(post.text)

app/views/posts/create.html.haml
= render "devise/shared/header"

.post-success
  .post-success__container
    .post-success__container__moji
      %h3
        投稿が完了しました。
    = link_to "戻る", posts_path, class: "post-success__container__btn"

app/views/posts/index.html.haml
= render "devise/shared/header"
.timeline
  .timeline-container
    .timeline-submit
      = link_to "投稿", new_post_path, class: "timeline-submit__btn"
    - @posts.each do |post|
      = render partial: "post", locals: { post: post }, class: "timeline-container__post-contents"
  .timeline__paginate

app/views/posts/new.html.haml
= render "devise/shared/header"

.posts
  .posts__container
    = form_tag('/posts', method: :post) do
      .post-form
        -# .post__image
        -#   %input{autofocus: "true", name: "image", placeholder: "Image URL", type: "text"}/
        
        %textarea{cols: "35", name: "text", placeholder: "入力する", rows: "3", class: "post-form__content"}
        %input{type: "submit", value: "投稿する", href: "/posts", class: "post-form__submit", data: { confirm: "投稿は削除、編集できませんがよろしいですか？" }}/
    %p.posts__new-posts
      最新の５件
    - @posts.each do |post|
      = render partial: "post", locals: { post: post }, class: "timeline-container__post-contents"

app/views/relationships/_follow.html.haml
- unless current_user == @user
  - if current_user.following?(@user)
    = form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: @user.id
      = f.submit 'フォロー中', class: 'follow-now'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: @user.id
      = f.submit 'フォロー', class: 'follows'

app/views/rooms/_room_index.html.haml
- @anotherEntries.each do |e|
  = link_to room_path(e.room.id) do
    = e.user.name
    とDMをしよう！

app/views/rooms/show.html.haml
= render "devise/shared/header"
.dm-main
  .dm-members
    .dm-members__lists
      .dm-members__list
        - @entries.each do |e|
          %a{href: "/users/#{e.user.id}"}
            = e.user.name
      .dm-members__moji
        %p さんとのダイレクトメッセージ
  .messages
    - if @messages.present?
      - @messages.each do |m|
        - if m.user_id == current_user.id
          .current-user__message
            .current-user__message__content
              = m.content
            .current-user__message__time
              = m.created_at.strftime("%Y/%m/%d %H:%M")
            -# %p.current-user__message__user
            -#   = m.user.name
        - else
          .frend-user__message
            .frend-user__message__content
              = m.content
            .frend-user__message__time
              = m.created_at.strftime("%Y/%m/%d %H:%M")
            %a.frend-user__message__user{href: "/users/#{m.user_id}"}
              = m.user.name
    - else
      %h3.text-center メッセージはまだありません
  .dm-footer
    = form_for @message do |f|
      .dm-footer__input
        = f.text_field :content, class: 'dm-footer__input__text', placeholder: 'メッセージを入力して下さい'
        = f.hidden_field :room_id, value: @room.id
        = f.label :image, class: 'dm-footer__input__image' do
          = fa_icon 'picture-o', class: 'icon'
          = f.file_field :image, class: 'hidden'
        = f.submit '送信', class: 'dm-footer__input__submit-btn'

app/views/users/dmRoom.html.haml
= render "devise/shared/header"
.dmRoom
  .dmRoom__container
    - if @anotherEntries.present?
      - @anotherEntries.each do |e|
        = link_to room_path(e.room.id) do
          .dmRoom__container__list
            = e.user.name
            さんとのDM
    - else
      %h3.dm-start-text 誰かとDMを始めてみよう！
      = link_to "暇人一覧", users_path, method: :get, class: "dm-start"
  .show-paginate__page
    = paginate(@anotherEntries)

app/views/users/edit.html.haml
= render "devise/shared/header"
.user-edit
  .edit-card
    %h1.edit-card__title
      アカウント編集
    = form_for(current_user) do |f|
      .edit-card__info
        -# .edit-card__info__image
          -# - if @user.image.present?
          -#   = image_tag @user.image.url
          -# - else
          -#   = image_tag "icon-red.png", size: "180x180", alt: "user-image"
        .edit-card__info__name
          = f.label :ユーザー名
          %br/
          = f.text_field :name, class: 'input-name', placeholder: "新しいユーザー名", autofocus: true, autocomplete: "name"
        .edit-card__info__email
          = f.label :email
          %br/
          = f.email_field :email, class: 'input-email', placeholder: "Email address", autofocus: true, autocomplete: "email"
        .edit-card__info__password__current
          = f.label :確認のため、パスワードを入力してください。
          %br/
          = f.password_field :current_password, class: 'input-password', placeholder: "変更前のパスワード",  autocomplete: "current-password"
      .edit-btn
        = f.submit '保存', class: 'edit-btn__save'
        = link_to "キャンセル", user_path, class: 'edit-btn__cancel', data: { confirm: "変更を破棄しますか？" }
      = link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class: "log-out-btn"

app/views/users/index.html.haml
-# %h1 Users#index
-# %p Find me in app/views/users/index.html.haml

= render "devise/shared/header"
.wrapper
  .body
    - if user_signed_in?
      .index__user
        - @users.each do |u|
          %a{href: "/users/#{u.id}"}
            .index__user__name
              = u.name 
        .users-paginate
          .users-paginate__page
            = paginate(@users)

app/views/users/show.html.haml
-# %h1 Users#show
-# %p Find me in app/views/users/show.html.haml
= render "devise/shared/header"
.user-contents
  .user-page
    .user-page__image
      = image_tag "icon-red.png", size: "180x180", alt: "user-image"
    .user-page__info
      .user-page__name
        = @user.name
      - @user ||= current_user
      .user-page__follow
        %p.user-page__follow__moji
          Follow
        %a.user-page__follow__count{href: "#{following_user_path(@user)}"}
          = @user.followings.count
      .user-page__follower
        %p.user-page__follower__moji
          Follower
        %a.user-page__follower__count{href: "#{followers_user_path(@user)}"}
          = @user.followers.count
      - if @user.id == current_user.id
        .current-user
          = link_to "編集", edit_user_path(current_user), class: "user-page__edit"
          = link_to "DM一覧", dmRoom_user_path, class: "user-page__dmRoom"
      - else
        - if @isRoom == true
          .frend-user
            .follow-btn
              = render "relationships/follow"
            .message-sender
              %a{href: "/rooms/#{@roomId}"}DM
        - else
          .frend-user
            .follow-btn
              = render "relationships/follow"
            = form_for @room do |f|
              = fields_for @entry do |e|
                = e.hidden_field :user_id, value: @user.id
              = f.submit "DM", class: 'message-start', data: { confirm: "DMを開始しますか？" }
  .user-post__card
    - @posts.each do |post|
      = render partial: "posts/post", locals: { post: post }
    .show-paginate
      .show-paginate__page
        = paginate(@posts)

app/views/users/show_follow.html.haml
= render "devise/shared/header"
.follow-members
  .follow-members__list
    - @user.followings.each do |user|
      .member= link_to user.name, user_path(user)
      %a{href: "/rooms/#{@roomId}"}

app/views/users/show_follower.html.haml
= render "devise/shared/header"
.follow-members
  .follow-members__list
    - @user.followers.each do |user|
      .member= link_to user.name, user_path(user)